# ════════════════════════════════════════════════════════════════════════════
#  DARK MODE — entity events. One fires on a specific lab / dealer / front and
#  PAUSES it until the player handles it (taps the entity and picks a choice).
#  Choice schema: [label, result_text, effects]
#    effects keys: cash, dirty, heat (global), eheat (this entity's own heat)
#    "s" inside effects = a coded special:
#      lose_crew | lose_product | bonus_product | free_supplies   (labs)
#      lose_held                                                  (dealers)
#      bust                                                       (seize this entity)
# ════════════════════════════════════════════════════════════════════════════

CREW_EVENTS = [
    {"i": "🔥", "t": "A burner left on overnight scorched part of a batch.", "c": [["Pay for quiet repairs", "Patched up, no questions.", {"cash": -1800}], ["Air it out and hope", "The neighbors noticed the smoke.", {"heat": 10}]]},
    {"i": "✨", "t": "Your cook nailed the recipe — this batch came out fat.", "c": [["Cash in", "Extra product stacked up.", {"s": "bonus_product"}]]},
    {"i": "🤒", "t": "A crew member's kid is sick; he needs a few days.", "c": [["Slip him some cash, take the time", "Loyalty earned.", {"cash": -1500, "eheat": -6}], ["Tell him to stay put", "He works angry.", {"eheat": 8}]]},
    {"i": "👃", "t": "A neighbor's complaining about a chemical smell.", "c": [["Pay them to mind their business", "Quiet again.", {"cash": -1200, "eheat": -10}], ["Ignore it", "They mentioned 'calling someone.'", {"eheat": 14}]]},
    {"i": "🧪", "t": "The cook wants pricier gear to bump the yield.", "c": [["Buy it", "Output up.", {"cash": -2500, "s": "bonus_product"}], ["Make do", "He sulks.", {"eheat": 5}]]},
    {"i": "🕵️", "t": "A guy's been parked outside the lab for two days straight.", "c": [["Lie low — pause the cook", "You go quiet.", {"eheat": -15}], ["Keep cooking", "Bold.", {"eheat": 12}]]},
    {"i": "💸", "t": "A crew member's been skimming product off the top.", "c": [["Cut him loose", "Message sent.", {"s": "lose_crew"}], ["Dock his pay, let it slide", "He owes you now.", {"cash": 600}]]},
    {"i": "⚡", "t": "The power company flagged the lab's insane electric usage.", "c": [["Pay a guy to reroute it", "Off the grid.", {"cash": -2200, "eheat": -8}], ["Risk it", "A flag's a flag.", {"eheat": 13}]]},
    {"i": "🚓", "t": "A member got picked up on an unrelated charge — and he's nervous.", "c": [["Post bail, keep him close", "He's grateful.", {"cash": -3000, "eheat": -5}], ["Leave him in there", "He might talk.", {"heat": 8}]]},
    {"i": "💵", "t": "Tearing out drywall, the crew found a previous tenant's cash stash.", "c": [["Split it and move on", "Nice bonus.", {"cash": 2000}]]},
    {"i": "🤝", "t": "A rival offered to buy your cook's recipe.", "c": [["Sell it", "Quick money, lasting regret.", {"cash": 6000, "eheat": 6}], ["Refuse", "You keep your edge.", {}]]},
    {"i": "😤", "t": "Crew morale's in the gutter; a couple are talking about walking.", "c": [["Hand out bonuses", "Spirits lift.", {"cash": -2500, "eheat": -8}], ["Let them grumble", "One might bail.", {"s": "lose_crew"}]]},
    {"i": "🐕", "t": "A member's dog got into the lab and ate part of the stash.", "c": [["Laugh it off", "Bad dog. Small loss.", {"s": "lose_product"}]]},
    {"i": "💡", "t": "The cook found a faster method on a sketchy forum.", "c": [["Let him try it", "It worked — big batch.", {"s": "bonus_product", "eheat": 5}], ["Too risky", "Stay the course.", {}]]},
    {"i": "🤫", "t": "An eager buyer keeps trying to score straight from the lab.", "c": [["Sell him a little", "Easy money, more eyes.", {"dirty": 1500, "eheat": 10}], ["Send him packing", "Keep the lab clean.", {"eheat": -4}]]},
    {"i": "🧯", "t": "A gas smell — could be a leak.", "c": [["Evacuate, lose the day", "Better safe.", {}], ["Keep working", "Reckless.", {"eheat": 9}]]},
    {"i": "🎉", "t": "The crew wants to throw a party after a big haul.", "c": [["Let them blow off steam", "Loud, but happy.", {"eheat": 8, }], ["Back to work", "Morale dips.", {"eheat": 4}]]},
    {"i": "📦", "t": "Your supplier shorted the last delivery.", "c": [["Demand a refund", "He coughs it up.", {"cash": 1200}], ["Eat it", "Whatever.", {}]]},
    {"i": "🌡️", "t": "The lab's AC died and the product's wilting in the heat.", "c": [["Fix it fast", "Saved.", {"cash": -1500}], ["Let it ride", "Some spoiled.", {"s": "lose_product"}]]},
    {"i": "📻", "t": "A member scored a police scanner off a buddy.", "c": [["Buy it off him", "Early warning system.", {"cash": -1000, "eheat": -12}], ["Pass", "No thanks.", {}]]},
    {"i": "🥊", "t": "Two crew members are feuding and it's slowing everything down.", "c": [["Buy the peace", "They cool off.", {"cash": -1000, "eheat": -5}], ["Let them sort it", "One storms off.", {"s": "lose_crew"}]]},
    {"i": "🧒", "t": "A neighborhood kid keeps loitering by the lab.", "c": [["Pay him to scram", "Gone.", {"cash": -300}], ["Ignore him", "Kids talk.", {"eheat": 7}]]},
    {"i": "💉", "t": "A member sampled way too much of the product.", "c": [["Dock his cut", "Lesson learned.", {"cash": 300}], ["Let it slide", "Morale up, stock down.", {"s": "lose_product"}]]},
    {"i": "🩹", "t": "A member got badly hurt in a lab accident.", "c": [["Pay for a quiet doctor", "He pulls through.", {"cash": -2500}], ["Dump him at the ER", "Questions get asked.", {"heat": 10}]]},
    {"i": "🍄", "t": "Mold crept into the grow.", "c": [["Salvage what you can", "Costly but saved.", {"cash": -1200}], ["Write it off", "Lost a chunk.", {"s": "lose_product"}]]},
    {"i": "🐀", "t": "Rats got into the lab.", "c": [["Call an exterminator", "Handled.", {"cash": -800}], ["Live with them", "They got into the stash.", {"s": "lose_product"}]]},
    {"i": "🛡️", "t": "A member turns out to be ex-military and locked the place down tight.", "c": [["Promote his role", "The lab runs quiet.", {"eheat": -12}]]},
    {"i": "💰", "t": "A local crew is demanding 'protection' money for the block.", "c": [["Pay the tax", "Peace, for a price.", {"cash": -2000, "eheat": -5}], ["Tell them no", "Now it's tense.", {"eheat": 12}]]},
    {"i": "🍺", "t": "A member got drunk and blabbed about the lab at a bar.", "c": [["Move the operation around", "Damage controlled.", {"cash": -1500, "eheat": -6}], ["Hope nobody listened", "Risky.", {"eheat": 14}]]},
    {"i": "🚪", "t": "A member wants out — and he knows where everything is.", "c": [["Pay him a clean exit", "He vanishes happy.", {"cash": -3000}], ["Let him walk angry", "He might snitch.", {"heat": 9, "s": "lose_crew"}]]},
    {"i": "👔", "t": "A member's parole officer made a surprise visit.", "c": [["Grease the PO", "Looked the other way.", {"cash": -1500, "eheat": -8}], ["Tough it out", "Close call.", {"eheat": 10}]]},
    {"i": "☣️", "t": "A whole batch came out contaminated.", "c": [["Dump it", "Total loss, but safe.", {"s": "lose_product"}], ["Cut it and sell anyway", "Risky for your name.", {"heat": 8}]]},
    {"i": "🎨", "t": "A member's an amateur artist and 'decorated' the lab to look lived-in.", "c": [["Let it ride — great cover", "Looks like a real home.", {"eheat": -8}]]},
    {"i": "🚗", "t": "A member's flashy new car is parked out front every day.", "c": [["Make him garage it", "Less attention.", {"eheat": -7}], ["Whatever", "Eyes drawn.", {"eheat": 9}]]},
    {"i": "👮", "t": "The neighbor's a retired cop who waves every morning.", "c": [["Befriend him", "Cookies for cover.", {"cash": -500, "eheat": -6}], ["Avoid him", "He's watching.", {"eheat": 7}]]},
    {"i": "💍", "t": "A member proposed to his girl in the lab parking lot. Crew's all hugs.", "c": [["Congratulate them", "Morale soars.", {"eheat": -5}]]},
    {"i": "📈", "t": "The cook's dialed in — double yield this run.", "c": [["Bank it", "Stacks.", {"s": "bonus_product"}]]},
    {"i": "🔌", "t": "A member rigged the supplies cheaper through a contact.", "c": [["Use his guy", "Saved a bundle.", {"cash": 1500}], ["Stick with your supplier", "Loyalty.", {}]]},
    {"i": "😴", "t": "The cook's burnt out and making mistakes.", "c": [["Give him a break", "Slower, but safer.", {"eheat": -6}], ["Push him", "Sloppy work.", {"heat": 6, "s": "lose_product"}]]},
    {"i": "🏍️", "t": "A member wants to bring his cousin onto the crew.", "c": [["Bring him in", "Extra hands.", {"cash": -800}], ["No new faces", "Keep it tight.", {}]]},
    {"i": "🎥", "t": "A true-crime YouTuber is filming 'abandoned houses' on your street.", "c": [["Pay him to film elsewhere", "Moved along.", {"cash": -1000, "eheat": -5}], ["Hope he skips yours", "Gamble.", {"eheat": 11}]]},
    {"i": "📬", "t": "A nosy mail carrier keeps asking who lives here.", "c": [["Tip him to forget", "He forgets.", {"cash": -400, "eheat": -4}], ["Stonewall", "Suspicious.", {"eheat": 6}]]},
    {"i": "💊", "t": "A member's hooked on the product and stealing to feed it.", "c": [["Get him clean (your dime)", "He owes you everything.", {"cash": -2000}], ["Cut him loose", "Liability gone.", {"s": "lose_crew"}]]},
    {"i": "🏆", "t": "Word on the street is your product is the best around.", "c": [["Lean into the rep", "Demand's up.", {"dirty": 2000, "eheat": 5}]]},
    {"i": "🚧", "t": "The city's doing road work right outside the lab.", "c": [["Pause until they're gone", "Lay low.", {"eheat": -10}], ["Work through it", "Lots of eyes.", {"eheat": 9}]]},
    {"i": "🐍", "t": "A member's been quietly working for a rival too.", "c": [["Cut the snake out", "Gone.", {"s": "lose_crew"}], ["Feed him false info", "Clever.", {"eheat": -3}]]},
    {"i": "🧰", "t": "A contact's selling stolen lab equipment dirt cheap.", "c": [["Buy the gear", "Free supplies.", {"cash": -1500, "s": "free_supplies"}], ["Pass", "Too hot.", {}]]},
    {"i": "🙏", "t": "A church group is doing a 'cleanup' walk down your block.", "c": [["Pause for the day", "Out of sight.", {"eheat": -6}], ["Keep cooking", "They lingered.", {"eheat": 7}]]},
    {"i": "🎰", "t": "The cook wants to gamble a batch on a risky 'super' method.", "c": [["Let him roll the dice", "It paid off huge.", {"s": "bonus_product", "eheat": 7}], ["Play it safe", "Steady as she goes.", {}]]},
    {"i": "📸", "t": "Someone slipped a photo of your lab under the door with a dollar sign on it.", "c": [["Pay the blackmail", "It goes away.", {"cash": -3500}], ["Call their bluff", "Risky game.", {"heat": 12}]]},
]

DEALER_EVENTS = [
    {"i": "🔫", "t": "Your dealer got robbed at gunpoint on the corner.", "c": [["Cover his loss", "He's loyal.", {"cash": -2500}], ["'That's the job'", "He eats it, and the grudge.", {"s": "lose_held", "eheat": 4}]]},
    {"i": "📦", "t": "A bulk buyer wants a discount for moving serious weight.", "c": [["Give the discount", "Volume's volume.", {"dirty": 2000}], ["Hold your price", "He walked.", {}]]},
    {"i": "🚓", "t": "Patrols just doubled on your dealer's corner.", "c": [["Move him to a new corner", "Off the radar.", {"cash": -800, "eheat": -12}], ["Hold the spot", "Risky.", {"eheat": 13}]]},
    {"i": "🌟", "t": "Your dealer built a loyal base — they only buy from him.", "c": [["Reward the hustle", "Sales climb.", {"dirty": 1800}]]},
    {"i": "🚑", "t": "A customer OD'd right on the corner.", "c": [["Lie low a few days", "Stay quiet.", {"eheat": -12}], ["Pay to make it disappear", "Handled, quietly.", {"cash": -2500}]]},
    {"i": "🔪", "t": "A rival dealer set up shop across the street.", "c": [["Run him off", "Your corner again.", {"eheat": 10}], ["Start a price war", "Margins thin.", {"dirty": -1500}]]},
    {"i": "💵", "t": "Your dealer's asking for a bigger cut.", "c": [["Bump his pay", "Motivated.", {"cash": -1200, "eheat": -4}], ["Deny him", "He slacks.", {"eheat": 6}]]},
    {"i": "⛓️", "t": "Your dealer got pinched — holding product and cash.", "c": [["Post bail", "Back on the corner.", {"cash": -3000}], ["Leave him", "Lost the dealer.", {"s": "bust"}]]},
    {"i": "🎤", "t": "A local celebrity copped from your dealer — word's spreading.", "c": [["Ride the hype", "Clout sells.", {"dirty": 2200}]]},
    {"i": "🤏", "t": "Your dealer's been skimming product.", "c": [["Cut his held cash", "Even.", {"s": "lose_held"}], ["Warn him once", "He straightens up.", {}]]},
    {"i": "🕶️", "t": "An obvious undercover tried to buy from your dealer.", "c": [["He clocked him — good eye", "Crisis dodged.", {"eheat": -10}], ["He almost sold", "Too close.", {"eheat": 14}]]},
    {"i": "🎪", "t": "There's a festival in town — foot traffic is insane.", "c": [["Flood the corner", "Huge day.", {"dirty": 2500, "eheat": 6}], ["Play it cool", "Steady.", {"dirty": 800}]]},
    {"i": "🐀", "t": "There's a snitch working your dealer's block.", "c": [["Pay to find out who", "Rooted out.", {"cash": -1500, "eheat": -8}], ["Ignore it", "Heat builds.", {"eheat": 12}]]},
    {"i": "🔫", "t": "Your dealer wants a piece for protection.", "c": [["Buy him one", "He feels safer.", {"cash": -1000, "eheat": -3}], ["No guns", "He's exposed.", {}]]},
    {"i": "💸", "t": "A customer paid your dealer in counterfeit bills.", "c": [["Track the guy down", "Got it back, plus interest.", {"cash": 1000}], ["Eat the loss", "Annoying.", {"s": "lose_held"}]]},
    {"i": "👑", "t": "A gang's claiming your dealer's territory.", "c": [["Pay tribute", "Uneasy peace.", {"dirty": -1500}], ["Fight for it", "Bloody, but yours.", {"eheat": 14}]]},
    {"i": "🏡", "t": "Your dealer found rich buyers out in the suburbs.", "c": [["Expand out there", "Big margins, more travel.", {"dirty": 2500, "eheat": 8}], ["Keep it local", "Safe.", {}]]},
    {"i": "🧒", "t": "A neighborhood kid wants to run product for your dealer.", "c": [["Put him to work", "Faster turnover.", {"dirty": 800, "eheat": 4}], ["Not a kid", "Pass.", {}]]},
    {"i": "🚧", "t": "Cops set up a checkpoint two blocks from the corner.", "c": [["Pause the dealer", "Wait it out.", {"eheat": -10}], ["Push through it", "Gutsy.", {"eheat": 12}]]},
    {"i": "💎", "t": "Your dealer's flashing chains and a new watch.", "c": [["Make him tone it down", "Lower profile.", {"eheat": -7}], ["Let him floss", "Eyes everywhere.", {"eheat": 9}]]},
    {"i": "📞", "t": "A regular customer turned informant.", "c": [["Buy his silence", "Quiet again.", {"cash": -2000, "eheat": -8}], ["Let it ride", "Risky.", {"eheat": 13}]]},
    {"i": "🔥", "t": "Your dealer sold out in hours and wants more product.", "c": [["Promise a restock", "He's hungry — good.", {"dirty": 1000}]]},
    {"i": "😡", "t": "Your dealer's got beef with a rival's runner.", "c": [["Squash it", "Peace bought.", {"cash": -1000, "eheat": -4}], ["Let it escalate", "Things get loud.", {"eheat": 11}]]},
    {"i": "📱", "t": "Your dealer's burner phone might be tapped.", "c": [["Buy him a fresh burner", "Clean line.", {"cash": -500, "eheat": -8}], ["Risk it", "Could be nothing.", {"eheat": 10}]]},
    {"i": "🙅", "t": "A do-gooder neighbor keeps calling the cops on the corner.", "c": [["Relocate the corner", "Fresh start.", {"cash": -800, "eheat": -10}], ["Stay put", "Calls keep coming.", {"eheat": 12}]]},
    {"i": "👬", "t": "Your dealer vouches for his brother to join up.", "c": [["Bring him on", "Two corners now.", {"cash": -1000, "dirty": 600}], ["Keep it lean", "No.", {}]]},
    {"i": "💪", "t": "A would-be robber tried your dealer — and lost.", "c": [["Take the guy's roll", "Bonus.", {"dirty": 1200}]]},
    {"i": "💋", "t": "Your dealer's been giving free product to a girl he likes.", "c": [["Dock his pay", "Cut it out.", {"cash": 400}], ["Young love", "Whatever.", {"s": "lose_held"}]]},
    {"i": "⛪", "t": "A protest is camped on your dealer's corner.", "c": [["Move for now", "Out of the spotlight.", {"eheat": -5}], ["Wait them out", "Slow days.", {"dirty": -500}]]},
    {"i": "🥂", "t": "Your dealer found clientele willing to pay double for discretion.", "c": [["Serve the high rollers", "Fat margins.", {"dirty": 2800, "eheat": 5}]]},
    {"i": "🩸", "t": "Your dealer beat down a customer who came up short.", "c": [["Let it stand", "Reputation, and heat.", {"eheat": 9}], ["Make him apologize (and pay)", "Cooler heads.", {"cash": -500, "eheat": -4}]]},
    {"i": "🤝", "t": "A rival's offering your dealer a better deal.", "c": [["Match it", "He stays.", {"cash": -1500}], ["Let him go", "Lost a good one.", {"s": "bust"}]]},
    {"i": "👁️", "t": "Your dealer spotted a stakeout van.", "c": [["Lie low", "Smart.", {"eheat": -12}], ["Ignore it", "They're watching.", {"eheat": 13}]]},
    {"i": "⛈️", "t": "A nasty storm killed corner traffic for days.", "c": [["Wait for the sun", "Slow stretch.", {"dirty": -400}]]},
    {"i": "🤕", "t": "Your dealer's little brother got jumped over the corner.", "c": [["Pay his medical", "Family first.", {"cash": -1500}], ["Send a message back", "Escalation.", {"eheat": 10}]]},
    {"i": "👮", "t": "A cop on the take wants his envelope.", "c": [["Pay up", "He waves you through.", {"cash": -2000, "eheat": -15}], ["Stiff him", "Bad idea.", {"eheat": 13}]]},
    {"i": "🚸", "t": "Your dealer's been selling near a school.", "c": [["Move him away", "Smarter.", {"eheat": -10}], ["Money's money", "Heat magnet.", {"eheat": 14}]]},
    {"i": "🎬", "t": "A film crew's shooting in the neighborhood — cameras everywhere.", "c": [["Pause the dealer", "Out of frame.", {"eheat": -7}], ["Work around them", "Risky.", {"eheat": 9}]]},
    {"i": "📈", "t": "Your dealer's corner became THE spot — volume's through the roof.", "c": [["Cash in", "Banner week.", {"dirty": 3000, "eheat": 8}], ["Throttle it", "Stay under the radar.", {"dirty": 1000}]]},
    {"i": "🆔", "t": "Your dealer lifted a wallet — there's a fat ID inside.", "c": [["Blackmail the guy", "Easy money.", {"cash": 2000, "eheat": 3}], ["Toss it", "Not worth it.", {}]]},
    {"i": "⏰", "t": "Your dealer's been slow getting product to the corner.", "c": [["Light a fire under him", "He moves quicker.", {"dirty": 600}], ["Let it slide", "Sales lag.", {}]]},
    {"i": "🌊", "t": "A new drug is the hot thing on the street right now.", "c": [["Capitalize fast", "You ride the wave.", {"dirty": 2200}]]},
    {"i": "🗣️", "t": "Your dealer got a tip about an upcoming raid.", "c": [["Pay for the details", "Forewarned.", {"cash": -1000, "eheat": -14}], ["Don't trust it", "Gamble.", {}]]},
    {"i": "😨", "t": "Your dealer's gotten so violent he's scaring off customers.", "c": [["Rein him in", "Sales recover.", {"eheat": -6}], ["Leave him be", "Fewer buyers.", {"dirty": -1000}]]},
    {"i": "🏃", "t": "A rival's best dealer wants to defect to you.", "c": [["Recruit him", "Big get.", {"cash": -2000, "dirty": 1500}], ["Pass", "Too much drama.", {}]]},
    {"i": "🏅", "t": "Your dealer just had his biggest day ever.", "c": [["Celebrate the win", "Stacks of dirty cash.", {"dirty": 2600}]]},
    {"i": "🧥", "t": "Your dealer wants a lookout kid on the corner with him.", "c": [["Hire the lookout", "Early warnings.", {"cash": -600, "eheat": -8}], ["He's fine solo", "Exposed.", {}]]},
    {"i": "🎲", "t": "Your dealer ran up a gambling debt with dangerous people.", "c": [["Cover it", "He owes you, not them.", {"cash": -2500}], ["His problem", "Distracted and scared.", {"eheat": 6}]]},
    {"i": "📰", "t": "A reporter's writing about 'open-air drug markets' in the area.", "c": [["Lay low until it blows over", "Quiet.", {"eheat": -8}], ["Business as usual", "Spotlight's on.", {"eheat": 11}]]},
    {"i": "💊", "t": "A customer wants to buy in massive quantity — too good to be true?", "c": [["Make the sale", "Huge, if it's real.", {"dirty": 3500, "eheat": 10}], ["Smells like a sting — pass", "Safe.", {"eheat": -4}]]},
]

_LAUNDRO = [
    {"i": "🧺", "t": "A washer broke down, spewing suds across the floor.", "c": [["Repair it", "Back in business.", {"cash": -1200}], ["Limp along", "Looks shady when half the machines are dead.", {"eheat": 7}]]},
    {"i": "📊", "t": "An auditor wants to review the laundromat's books.", "c": [["Grease him", "Books look spotless.", {"cash": -2500, "eheat": -10}], ["Let him dig", "Uncomfortable.", {"eheat": 14}]]},
    {"i": "🧦", "t": "A customer found a wad of your cash stuffed in a dryer.", "c": [["Buy it back quietly", "Recovered.", {"cash": -800}], ["Let them keep it", "Cheaper than questions.", {"eheat": 5}]]},
    {"i": "🪙", "t": "The coin counter jammed mid-count.", "c": [["Fix it", "Counts again.", {"cash": -500}], ["Count by hand", "Slow week.", {}]]},
    {"i": "🤨", "t": "A regular asked why it's always empty but the registers are full.", "c": [["Comp his laundry for a month", "He stops wondering.", {"cash": -600, "eheat": -6}], ["Deflect", "He's suspicious.", {"eheat": 8}]]},
    {"i": "📋", "t": "Surprise health inspection.", "c": [["Bribe the inspector", "All clear.", {"cash": -2000, "eheat": -8}], ["Risk it", "He frowned.", {"eheat": 11}]]},
    {"i": "🧴", "t": "Your detergent supplier hiked prices.", "c": [["Pay the new rate", "Keep the doors open.", {"cash": -700}], ["Switch suppliers", "Saved a little.", {"cash": 300}]]},
    {"i": "🛏️", "t": "A homeless man's been sleeping in the laundromat overnight.", "c": [["Pay him to move on", "Quiet again.", {"cash": -300}], ["Let him stay", "Draws attention.", {"eheat": 6}]]},
    {"i": "💼", "t": "Your dirty manager's been skimming the wash.", "c": [["Replace him", "Clean slate.", {}], ["Cut his pay", "He behaves.", {"cash": 500}]]},
    {"i": "⚡", "t": "The utility company flagged the laundromat's huge water-and-power bills.", "c": [["Pay a guy to massage the meters", "Numbers normalize.", {"cash": -1800, "eheat": -10}], ["Ignore it", "A flag's a flag.", {"eheat": 12}]]},
    {"i": "🎬", "t": "A film crew wants to shoot a scene in your laundromat.", "c": [["Rent it to them", "Easy clean money.", {"cash": 1500}], ["Decline", "Too many eyes.", {"eheat": -3}]]},
    {"i": "💰", "t": "Your manager wants a raise to keep quiet.", "c": [["Pay up", "Loyalty bought.", {"cash": -1500, "eheat": -4}], ["Refuse", "He's resentful.", {"eheat": 8}]]},
    {"i": "🎨", "t": "Kids tagged graffiti all over the machines.", "c": [["Repaint it", "Respectable again.", {"cash": -600}], ["Leave it", "Looks like a front.", {"eheat": 6}]]},
    {"i": "👮", "t": "A beat cop does his laundry here every week.", "c": [["Befriend him", "A cop who likes you.", {"cash": -400, "eheat": -10}], ["Stay nervous", "He notices things.", {"eheat": 6}]]},
    {"i": "🌊", "t": "Too much cash is flowing through — it's starting to look obvious.", "c": [["Throttle the wash", "Less suspicious.", {"eheat": -10}], ["Keep pushing", "Greedy.", {"eheat": 12}]]},
    {"i": "🚿", "t": "A pipe burst and flooded the place.", "c": [["Emergency repair", "Reopened fast.", {"cash": -2000}], ["Close for repairs", "Lost wash days.", {}]]},
    {"i": "👨‍👩‍👦", "t": "Your manager wants to bring his 'cousin' on staff.", "c": [["Hire the cousin", "More hands.", {"cash": -500}], ["No new faces", "Keep it tight.", {}]]},
    {"i": "📣", "t": "A customer filed a complaint with the city.", "c": [["Smooth it over", "Withdrawn.", {"cash": -1000, "eheat": -5}], ["Ignore it", "City's looking now.", {"eheat": 9}]]},
    {"i": "💡", "t": "Your manager figured out a slicker way to run the cash.", "c": [["Implement it", "Cleaner, cooler.", {"eheat": -12}]]},
    {"i": "🔫", "t": "Someone tried to rob the laundromat after hours.", "c": [["Beef up security", "Safe.", {"cash": -1200, "eheat": -3}], ["Let it go", "They got the till.", {"cash": -1500}]]},
    {"i": "😰", "t": "Your manager's getting cold feet about the whole thing.", "c": [["Reassure him (with cash)", "He's calm.", {"cash": -1000}], ["Let him stew", "He might walk.", {"eheat": 7}]]},
    {"i": "🏛️", "t": "An IRS notice arrived about the laundromat's income.", "c": [["Put your accountant on it", "Filed clean.", {"cash": -1500, "eheat": -8}], ["Toss it", "Bold.", {"eheat": 14}]]},
    {"i": "🎉", "t": "Idea: a grand-reopening promo to explain the foot traffic.", "c": [["Throw the promo", "Great cover story.", {"cash": -1000, "eheat": -8}], ["Skip it", "Stay low-key.", {}]]},
    {"i": "🏪", "t": "A rival laundromat opened a block away.", "c": [["Undercut their prices", "Customers stay.", {"cash": -500}], ["Ignore them", "Whatever.", {}]]},
    {"i": "🔧", "t": "The repair guy noticed way more cash than a laundromat should hold.", "c": [["Tip him to forget", "Forgotten.", {"cash": -700, "eheat": -5}], ["Act normal", "He gave you a look.", {"eheat": 7}]]},
    {"i": "🎟️", "t": "A lotto winner cashed out nearby and crowds are wandering in.", "c": [["Welcome the crowd", "Great cover.", {"eheat": -6}]]},
    {"i": "📷", "t": "Your manager wants better cameras for the operation.", "c": [["Install them", "Eyes on everything.", {"cash": -900, "eheat": -4}], ["Too pricey", "Pass.", {}]]},
    {"i": "🕵️", "t": "A 'customer' keeps photographing the place.", "c": [["Confront him", "He scrams.", {"eheat": -6}], ["Ignore him", "Documented.", {"eheat": 10}]]},
    {"i": "✨", "t": "End-of-month books came out suspiciously perfect.", "c": [["Rough them up a little", "Believable.", {"cash": -800, "eheat": -6}], ["Leave them", "Too clean reads as fake.", {"eheat": 8}]]},
    {"i": "🧼", "t": "A big neighboring business wants to do all their towels here — steady cash cover.", "c": [["Take the contract", "Perfect legitimacy.", {"cash": 1200, "eheat": -6}]]},
]

_CARWASH = [
    {"i": "🩸", "t": "A car came through with something dark staining the trunk.", "c": [["Detail it, ask nothing", "Spotless. Charge extra.", {"cash": 1500, "eheat": 5}], ["Refuse the job", "Bad for repeat business.", {}]]},
    {"i": "💧", "t": "The water bill came back astronomically high.", "c": [["Pay it", "Doors stay open.", {"cash": -1500}], ["Dispute it loudly", "Drew a city audit.", {"eheat": 8}]]},
    {"i": "💊", "t": "A detailer found a stash tucked in a customer's car.", "c": [["Keep it quiet, pocket it", "Bonus.", {"dirty": 1000}], ["Leave it be", "Not your business.", {}]]},
    {"i": "📋", "t": "An inspector's checking the wash's equipment.", "c": [["Bribe him", "All good.", {"cash": -2000, "eheat": -8}], ["Let him inspect", "Tense.", {"eheat": 11}]]},
    {"i": "💎", "t": "A luxury car owner tipped big for a flawless detail.", "c": [["Bank the tip", "Easy clean money.", {"cash": 1200}]]},
    {"i": "💼", "t": "Your dirty manager's skimming the wash money.", "c": [["Replace him", "Fresh start.", {}], ["Dock him", "He shapes up.", {"cash": 500}]]},
    {"i": "🔧", "t": "The wash conveyor jammed and bent a customer's bumper.", "c": [["Pay for the repair + fix it", "Reputation saved.", {"cash": -1400}], ["Deny it", "Angry customer, bad word.", {"eheat": 5}]]},
    {"i": "👮", "t": "A cop gets his cruiser washed here every shift.", "c": [["Comp him, befriend him", "A friend in blue.", {"cash": -400, "eheat": -10}], ["Stay wary", "He's around a lot.", {"eheat": 6}]]},
    {"i": "🌊", "t": "Too much cash is moving through to be believable.", "c": [["Slow the wash", "Stay under the radar.", {"eheat": -10}], ["Keep it flowing", "Greedy.", {"eheat": 12}]]},
    {"i": "🏎️", "t": "A gang wants to run a getaway car through to lose evidence.", "c": [["Charge a premium", "Dirty money, more risk.", {"dirty": 2000, "eheat": 9}], ["Refuse", "Not worth it.", {}]]},
    {"i": "💰", "t": "Your manager's angling for a raise.", "c": [["Pay him", "Happy and quiet.", {"cash": -1500, "eheat": -4}], ["Say no", "Resentful.", {"eheat": 7}]]},
    {"i": "🌟", "t": "A celebrity's car rolled in — the lot's buzzing.", "c": [["Milk the buzz", "Great legit cover.", {"cash": 800, "eheat": -5}]]},
    {"i": "🔑", "t": "Vandals keyed a row of cars in your lot overnight.", "c": [["Cover the damage", "Customers placated.", {"cash": -1000}], ["Not your problem", "Reviews tank.", {"eheat": 4}]]},
    {"i": "📡", "t": "A detailer found a GPS tracker stuck under a regular's car.", "c": [["Quietly remove it", "Whoever it was is blind now.", {"eheat": -8}], ["Leave it alone", "Eyes on your lot.", {"eheat": 9}]]},
    {"i": "♻️", "t": "The water-reclamation system got flagged by the city.", "c": [["Pay to bring it 'to code'", "Compliant.", {"cash": -1300, "eheat": -6}], ["Ignore the notice", "Risky.", {"eheat": 10}]]},
    {"i": "🧽", "t": "A 'detailing' job is clearly evidence cleanup.", "c": [["Charge triple, no questions", "Dirty money in.", {"dirty": 1800, "eheat": 6}], ["Turn it away", "Clean conscience.", {}]]},
    {"i": "😰", "t": "Your manager's nerves are fraying.", "c": [["Calm him with cash", "Steady.", {"cash": -1000}], ["Let him sweat", "He's a flight risk.", {"eheat": 6}]]},
    {"i": "🔫", "t": "Someone tried to stick up the wash at close.", "c": [["Add security", "Protected.", {"cash": -1200}], ["Hand over the till", "Lost the day's take.", {"cash": -1500}]]},
    {"i": "🏛️", "t": "The IRS sent a letter about the wash's revenue.", "c": [["Accountant handles it", "Clean.", {"cash": -1500, "eheat": -8}], ["Shred it", "Bold.", {"eheat": 14}]]},
    {"i": "🏪", "t": "A new automatic car-wash chain opened nearby.", "c": [["Drop your prices", "Hold the customers.", {"cash": -500}], ["Ride it out", "Some drift away.", {}]]},
    {"i": "🧴", "t": "Your soap and wax supplier raised prices.", "c": [["Eat the cost", "Keep washing.", {"cash": -600}], ["Find a cheaper guy", "Saved a bit.", {"cash": 300}]]},
    {"i": "🎤", "t": "A reporter's asking how a car wash pulls in this much cash.", "c": [["Deflect with charm", "Story dropped.", {"cash": -800, "eheat": -5}], ["No comment", "She's curious now.", {"eheat": 9}]]},
    {"i": "💡", "t": "Your manager found a way to push more cash through per day.", "c": [["Run with it", "More wash, less heat.", {"eheat": -10}]]},
    {"i": "🧒", "t": "A part-time kid saw something he shouldn't have in the back.", "c": [["Pay for his silence", "Quiet.", {"cash": -600, "eheat": -4}], ["Hope he forgets", "Kids talk.", {"eheat": 8}]]},
    {"i": "📦", "t": "Someone left a 'package' in a car for you to pass along.", "c": [["Handle the drop", "Paid well for it.", {"dirty": 1500, "eheat": 5}], ["Stay out of it", "Not today.", {}]]},
    {"i": "👨‍👩‍👦", "t": "Your manager wants to put his cousin on the crew.", "c": [["Hire him", "Extra hands.", {"cash": -500}], ["No", "Keep it lean.", {}]]},
    {"i": "📈", "t": "A car-show convoy rolled through — record volume today.", "c": [["Cash in", "Banner day.", {"cash": 1500, "eheat": -3}]]},
    {"i": "👮", "t": "A cop did a 'random' walkthrough of the back bays.", "c": [["Slip him something", "He moves on.", {"cash": -1500, "eheat": -6}], ["Let him look", "Sweated it out.", {"eheat": 9}]]},
    {"i": "🧍", "t": "Your best detailer quit out of nowhere.", "c": [["Hire a replacement fast", "Back to speed.", {"cash": -800}], ["Run short-staffed", "Slower, sloppier.", {}]]},
    {"i": "✨", "t": "The books came out too perfect again.", "c": [["Add some believable mess", "Reads real.", {"cash": -700, "eheat": -6}], ["Leave them", "Suspiciously clean.", {"eheat": 8}]]},
]

_PIZZERIA = [
    {"i": "🐀", "t": "A health inspector swears he saw a rat in the kitchen.", "c": [["Slip him an envelope", "He saw nothing.", {"cash": -2000, "eheat": -8}], ["Argue it", "He's writing it up.", {"eheat": 11}]]},
    {"i": "⭐", "t": "A food critic showed up unannounced.", "c": [["Comp the best table", "Glowing review — great cover.", {"cash": -300, "eheat": -7}], ["Treat him like anyone", "Mediocre write-up.", {}]]},
    {"i": "🕴️", "t": "A made man wants a standing table every Friday.", "c": [["Comp him forever", "A powerful friend.", {"cash": -500, "eheat": -6}], ["Politely refuse", "You don't want that enemy.", {"eheat": 5}]]},
    {"i": "💵", "t": "The register's running thousands 'over' — too much to explain.", "c": [["Quietly fix the books", "Balanced.", {"cash": -1000, "eheat": -6}], ["Pocket the overage", "Risky but tasty.", {"cash": 1500, "eheat": 7}]]},
    {"i": "💼", "t": "Your dirty manager's been skimming the register.", "c": [["Replace him", "Clean slate.", {}], ["Dock his pay", "He behaves.", {"cash": 500}]]},
    {"i": "🔥", "t": "A grease fire flared up in the kitchen.", "c": [["Repair quietly", "Reopened.", {"cash": -1800}], ["Close for cleanup", "Lost days.", {}]]},
    {"i": "👮", "t": "A cop eats here almost every night.", "c": [["Keep his slices free", "A cop in your corner.", {"cash": -300, "eheat": -10}], ["Charge him full", "He lingers and watches.", {"eheat": 5}]]},
    {"i": "🌊", "t": "Too much cash through the register is getting hard to explain.", "c": [["Slow the laundering", "Believable books.", {"eheat": -10}], ["Keep washing big", "Greedy.", {"eheat": 12}]]},
    {"i": "🛵", "t": "A delivery driver wandered into the back room.", "c": [["Pay for his silence", "He forgets.", {"cash": -800, "eheat": -5}], ["Brush it off", "He saw plenty.", {"eheat": 9}]]},
    {"i": "💰", "t": "Your manager wants a bigger cut to keep quiet.", "c": [["Pay up", "Loyalty secured.", {"cash": -1500, "eheat": -4}], ["Refuse", "He's bitter.", {"eheat": 8}]]},
    {"i": "🌟", "t": "A celebrity ordered delivery and posted about it.", "c": [["Ride the clout", "Packed house, great cover.", {"cash": 1200, "eheat": -4}]]},
    {"i": "🤢", "t": "A customer claims they got food poisoning.", "c": [["Settle quietly", "Lawsuit avoided.", {"cash": -1500}], ["Deny it", "Bad reviews, city sniffing.", {"eheat": 8}]]},
    {"i": "🍽️", "t": "Idea: a 'catering arm' to push more cash through cleanly.", "c": [["Launch catering", "More wash, less suspicion.", {"cash": -1000, "eheat": -10}], ["Skip it", "Stay simple.", {}]]},
    {"i": "📰", "t": "A 'local eats' reporter is asking oddly specific money questions.", "c": [["Charm her off the topic", "Story's about the marinara now.", {"cash": -700, "eheat": -5}], ["Stonewall", "She smells something.", {"eheat": 9}]]},
    {"i": "🔫", "t": "Someone tried to rob the place at closing.", "c": [["Add security", "Locked down.", {"cash": -1200}], ["Hand over the register", "Lost the night's cash.", {"cash": -1500}]]},
    {"i": "🏛️", "t": "An IRS audit letter landed for the restaurant.", "c": [["Accountant on it", "Filed clean.", {"cash": -1500, "eheat": -8}], ["Ignore it", "Reckless.", {"eheat": 14}]]},
    {"i": "🏪", "t": "A rival pizzeria opened down the street.", "c": [["Run a promo", "Customers stay loyal.", {"cash": -600}], ["Let it ride", "Whatever.", {}]]},
    {"i": "🧀", "t": "Your cheese supplier jacked up prices.", "c": [["Pay the markup", "Keep the ovens hot.", {"cash": -700}], ["Switch suppliers", "Saved a little.", {"cash": 300}]]},
    {"i": "😰", "t": "Your manager's getting paranoid about the operation.", "c": [["Settle his nerves", "Calm.", {"cash": -1000}], ["Let him stew", "Flight risk.", {"eheat": 7}]]},
    {"i": "🤨", "t": "A regular noticed the place is half-empty but the register's always packed.", "c": [["Comp his meals a while", "He stops counting heads.", {"cash": -500, "eheat": -5}], ["Brush him off", "He wonders.", {"eheat": 8}]]},
    {"i": "🚒", "t": "A kitchen fire scare brought the trucks out front.", "c": [["Smooth it over with the inspectors", "No follow-up.", {"cash": -1200, "eheat": -5}], ["Hope they don't dig", "Eyes on the place.", {"eheat": 9}]]},
    {"i": "📦", "t": "A 'catering order' is really a cash drop for a friend.", "c": [["Handle the handoff", "Paid nicely.", {"dirty": 1800, "eheat": 5}], ["Decline", "Not tonight.", {}]]},
    {"i": "👨‍👩‍👦", "t": "Your manager wants to bring his cousin on as a 'waiter.'", "c": [["Hire him", "Family business.", {"cash": -500}], ["No", "Keep it tight.", {}]]},
    {"i": "🎂", "t": "A huge catering gig came in — perfect legit volume.", "c": [["Take the gig", "Beautiful cover.", {"cash": 1500, "eheat": -6}]]},
    {"i": "🦸", "t": "A customer choked and your staff saved him — local hero story.", "c": [["Lean into the good press", "Reputation gold.", {"eheat": -8}]]},
    {"i": "🪳", "t": "A photo of a roach in a booth is going viral online.", "c": [["Pay for PR cleanup", "Buried.", {"cash": -1500, "eheat": -5}], ["Wait it out", "City took notice.", {"eheat": 10}]]},
    {"i": "🎈", "t": "A cop's kid wants his birthday party here.", "c": [["Host it free", "The whole precinct loves you.", {"cash": -600, "eheat": -10}], ["Charge them", "Missed an opportunity.", {}]]},
    {"i": "✨", "t": "The books came out suspiciously spotless this month.", "c": [["Add believable losses", "Reads real.", {"cash": -700, "eheat": -6}], ["Leave them", "Too perfect.", {"eheat": 8}]]},
    {"i": "🤝", "t": "An old family friend wants to wash his money through you too — for a cut.", "c": [["Take his business", "Extra dirty money flowing.", {"dirty": 2000, "eheat": 6}], ["Politely decline", "Your operation stays yours.", {}]]},
    {"i": "🍕", "t": "You hosted a pizza-eating contest and the place was mobbed.", "c": [["Soak up the crowd", "Cover and cash.", {"cash": 1000, "eheat": -5}]]},
]

LAUNDER_EVENTS = {"laundromat": _LAUNDRO, "car_wash": _CARWASH, "pizzeria": _PIZZERIA}
